# -*- coding: utf-8 -*-
"""Tutor_medico_github.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WE7zrFb7C9_7tdQumaz-5m13vaRzwBcS
"""
import streamlit as st
import google.generativeai as genai
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision.transforms as transforms
from PIL import Image
import pandas as pd

# ==========================================
# CONFIGURACIÓN DE LA PÁGINA
# ==========================================
st.set_page_config(page_title="Tutor Médico", page_icon="🧠", layout="wide")
st.title("¡HOLA! El servidor está vivo.") 

# ==========================================
# CONFIGURACIÓN DE IA (GEMINI)
# ==========================================
API_KEY = "AQ.Ab8RN6IId32Pq66MPZ48lCQOwfNesmN8EDVeZFCn_1FvJx5yBg"
genai.configure(api_key=API_KEY)

nombre_modelo_permitido = 'gemini-pro'
try:
    for m in genai.list_models():
        if 'generateContent' in m.supported_generation_methods:
            nombre_modelo_permitido = m.name
            break
except Exception as e:
    st.sidebar.error("Aviso: No se pudo escanear los modelos.")

modelo_llm = genai.GenerativeModel(nombre_modelo_permitido)

# ==========================================
# DEFINICIÓN DE TU RED NEURONAL (PYTORCH)
# ==========================================
class CNN_Tumores(nn.Module):
    def __init__(self):
        super(CNN_Tumores, self).__init__()
        self.conv1 = nn.Conv2d(3, 32, kernel_size=3, padding=1)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1)
        self.conv3 = nn.Conv2d(64, 128, kernel_size=3, padding=1)
        self.fc1 = nn.Linear(128 * 16 * 16, 512)
        self.fc2 = nn.Linear(512, 4)
        self.dropout = nn.Dropout(0.3)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = self.pool(F.relu(self.conv3(x)))
        x = torch.flatten(x, 1)
        x = self.dropout(F.relu(self.fc1(x)))
        x = self.fc2(x)
        return x

# Usamos st.cache_resource para que el modelo pesado se cargue SOLO UNA VEZ en la memoria web
@st.cache_resource
def cargar_modelo():
    dispositivo = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    modelo = CNN_Tumores().to(dispositivo)
    # Carga los pesos desde Google Drive
    ruta_guardado = 'modelo_tumores_pytorch.pth'
    modelo.load_state_dict(torch.load(ruta_guardado, map_location=dispositivo))
    modelo.eval()
    return modelo, dispositivo

# Cargamos el modelo
net, device = cargar_modelo()

# Transformaciones idénticas a tu código de entrenamiento
transform_test = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])

clases_tumor = ['glioma_tumor', 'meningioma_tumor', 'no_tumor', 'pituitary_tumor']
nombres_b = {
    "glioma_tumor": "Tumor tipo Glioma",
    "meningioma_tumor": "Tumor tipo Meningioma",
    "no_tumor": "Paciente Sano (Sin Tumor)",
    "pituitary_tumor": "Tumor Pituitario"
}

# ==========================================
# MEMORIA DE LA APP Y MENÚ
# ==========================================
if "chat_history" not in st.session_state: st.session_state.chat_history = []
if "flashcard_index" not in st.session_state: st.session_state.flashcard_index = 0
if "flashcard_flipped" not in st.session_state: st.session_state.flashcard_flipped = False
if "thea_index" not in st.session_state: st.session_state.thea_index = 0
if "thea_ans" not in st.session_state: st.session_state.thea_ans = None
if "thea_feedback" not in st.session_state: st.session_state.thea_feedback = False

with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/3003/3003261.png", width=100)
    st.title("Tutor Médico")
    menu = st.radio("Navegación", [" Teoría Profunda", " Diagnóstico por Imagen", " Tutor Virtual", " Zona de Estudio"])

# ==========================================
# SECCIÓN 1: DIAGNÓSTICO (Conectado a tu CNN)
# ==========================================
if menu == " Diagnóstico por Imagen":
    st.title(" Laboratorio Clínico de IA")
    st.markdown("Sube una resonancia para que tu modelo de PyTorch la clasifique y Gemini la explique.")

    archivo_subido = st.file_uploader("Sube el archivo MRI", type=['png', 'jpg', 'jpeg'])

    if archivo_subido is not None:
        col_img, col_res = st.columns([1, 2])

        with col_img:
            img = Image.open(archivo_subido).convert('RGB')
            st.image(img, caption="Radiografía Ingresada", use_container_width=True)

        with col_res:
            if st.button("Procesar Imagen", use_container_width=True):
                with st.spinner("Procesando tu Red Neuronal..."):
                    img_tensor = transform_test(img).unsqueeze(0).to(device)

                    with torch.no_grad():
                        outputs = net(img_tensor)
                        probabilidades = F.softmax(outputs, dim=1)
                        porcentaje, indice = torch.max(probabilidades, 1)

                        clase_original = clases_tumor[indice.item()]
                        diagnostico_cnn = nombres_b.get(clase_original, clase_original)
                        confianza_cnn = porcentaje.item() * 100

                    st.success("¡Análisis Completado!")
                    st.metric(label="Predicción de TU Modelo", value=diagnostico_cnn, delta=f"Confianza: {confianza_cnn:.2f}%")

                with st.spinner("Solicitando retroalimentación a Gemini..."):
                    contexto = f"Eres el Tutor Médico. Una CNN real diagnosticó la imagen como '{diagnostico_cnn}' con {confianza_cnn:.2f}% de certeza. Explica al alumno universitario por qué se forma este tumor y qué ve usualmente una red neuronal en la resonancia. Sé conciso."
                    try:
                        respuesta = modelo_llm.generate_content(contexto)
                        st.markdown("### 🎓 Análisis del Tutor Médico")
                        st.info(respuesta.text)
                    except Exception as e:
                        st.error(f"Falla en la API de Google. Detalles del error: {str(e)}")

# ==========================================
# SECCIÓN 2: TEORÍA PROFUNDA (ENCICLOPEDIA)
# ==========================================
elif menu == " Teoría Profunda":
    st.title(" Enciclopedia de Inteligencia Artificial y Neurología")
    st.markdown("Bienvenido al glosario técnico y médico detallado. Esta sección desglosa el marco teórico basado en la investigación *'Convolutional neural network with hyperparameter tuning for brain tumor classification'* (Minarno et al., 2021). [Ver Documentación de PyTorch](https://pytorch.org/docs/stable/index.html).")

    # --- DESPLEGABLE 1: EL ARTÍCULO Y EL DATASET ---
    with st.expander(" 1. El Estudio de Investigación y el Dataset", expanded=True):
        st.markdown("### El Problema Médico")
        st.markdown("La identificación temprana de tumores cerebrales es fundamental para aumentar la tasa de supervivencia de los pacientes. El diagnóstico manual a partir de imágenes de Resonancia Magnética (MRI) es un proceso propenso a errores humanos, requiere mucho tiempo y depende de la fatiga del radiólogo. Por ello, el estudio propone automatizar este proceso mediante Redes Neuronales Convolucionales (CNN) y la sintonización de hiperparámetros.")

        st.markdown("### Análisis del Dataset de Kaggle")
        st.markdown("Para entrenar el modelo predictivo, la investigación recopiló un total de **3264 imágenes MRI**, divididas matemáticamente en un 80% para entrenamiento, 10% para validación y 10% para pruebas. La distribución exacta es la siguiente:")

        datos_grafica = pd.DataFrame({
            'Categoría': ['Glioma', 'Meningioma', 'Tumor Pituitario', 'Cerebro Sano'],
            'Cantidad': [926, 937, 901, 500]
        })
        st.bar_chart(datos_grafica.set_index('Categoría'))
        st.caption("Gráfico: Distribución balanceada de las 3264 imágenes utilizadas en el estudio base.")

    #  DESPLEGABLE 2: PATOLOGÍAS
    with st.expander(" 2. Patología: Tipos de Tumores Cerebrales (MRI)"):
        st.markdown("La Resonancia Magnética (MRI) utiliza potentes campos magnéticos para mapear la anatomía interna. El modelo clasifica las imágenes en 4 categorías clínicas:")

        col_mri1, col_mri2 = st.columns(2)
        with col_mri1:
            st.markdown("""
            * **Glioma:** Tumores que nacen en las células gliales (el "pegamento" que sostiene a las neuronas). Pueden ocurrir tanto en el cerebro como en la médula espinal. Tienden a ser invasivos y de crecimiento muy rápido, infiltrándose en el tejido cerebral circundante.
            * **Meningioma:** Se originan en las meninges, que son las tres capas de membranas protectoras que recubren el cerebro y la médula. Generalmente son tumores benignos (no cancerosos) y de crecimiento muy lento.
            """)
        with col_mri2:
            st.markdown("""
            * **Tumor Pituitario:** También llamados adenomas hipofisarios, se desarrollan en la glándula pituitaria (ubicada en la base del cerebro). Aunque no suelen ser cancerosos, su peligro radica en que alteran masivamente la producción hormonal del cuerpo.
            * **Cerebro Sano:** Tejido cerebral donde se conserva la simetría ventricular y no existen masas hiperintensas anómalas.
            """)
        st.image("https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Normal_axial_T2-weighted_MR_image_of_the_brain.jpg/512px-Normal_axial_T2-weighted_MR_image_of_the_brain.jpg", width=250, caption="Corte Axial de un MRI Sano (Referencia)")

    # DESPLEGABLE 3: PREPROCESAMIENTO
    with st.expander(" 3. Pipeline: Preprocesamiento y Data Augmentation"):
        st.markdown("Antes de que la red neuronal pueda 'ver' las imágenes, estas deben transformarse en matrices numéricas perfectas y estandarizadas.")

        st.subheader("Fase A: Redimensionamiento (Resize) y Normalización")
        st.markdown("Las imágenes médicas originales solían tener dimensiones de 512x512 píxeles. Procesar esto consumiría una cantidad excesiva de RAM de video (VRAM). Por lo tanto, el primer paso es comprimirlas a tensores de **128x128 píxeles**.")
        st.markdown(r"Luego, aplicamos la **Normalización**. Los píxeles tienen valores de 0 a 255. La red neuronal trabaja mejor con números pequeños, por lo que estandarizamos estos valores entre -1 y 1 usando una media ($\mu$) y desviación estándar ($\sigma$) de 0.5:")
        st.latex(r"X_{norm} = \frac{X - \mu}{\sigma} = \frac{X - 0.5}{0.5}")

        st.subheader("Fase B: Aumento de Datos (Data Augmentation)")
        st.markdown("""
        El sobreajuste (*Overfitting*) ocurre cuando la red 'memoriza' de memoria las 3264 imágenes en lugar de aprender a detectar la forma del tumor. Para evitarlo, aplicamos deformaciones aleatorias en tiempo real durante el entrenamiento:
        * **Random Rotation:** Rota la imagen al azar unos pocos grados.
        * **Random Horizontal Flip:** Voltea la imagen como si fuera un espejo.
        * **Random Zoom / Shift:** Desplaza o acerca la imagen.
        De esta manera, la red neuronal nunca ve la misma imagen exacta dos veces.
        """)

    #  DESPLEGABLE 4: LA CNN
    with st.expander(" 4. Arquitectura de Extracción (CNN)"):
        st.markdown("El núcleo matemático del proyecto es una **Red Neuronal Convolucional**. Su objetivo es extraer patrones visuales (bordes, contrastes, texturas) sin necesidad de que un humano se los programe.")

        st.image("https://upload.wikimedia.org/wikipedia/commons/6/63/Typical_cnn.png", caption="Arquitectura clásica de una CNN", use_container_width=True)

        st.subheader("La Operación Convolucional (Conv2D)")
        st.markdown("Un pequeño filtro matricial (ej. de 3x3 píxeles) se desliza sobre la imagen realizando el producto punto entre sus valores y los de la imagen. Esto genera un 'Mapa de Características'.")
        st.latex(r"S(i,j) = (I * K)(i,j) = \sum_m \sum_n I(i-m, j-n) K(m,n)")

        col_cnn1, col_cnn2 = st.columns(2)
        with col_cnn1:
            st.markdown("**Activación No Lineal (ReLU):**")
            st.image("https://upload.wikimedia.org/wikipedia/commons/c/c9/Relu.png", width=150)
            st.latex(r"f(x) = \max(0, x)")
            st.markdown("La función *Rectified Linear Unit* reemplaza todos los píxeles negativos por ceros. Esto le da a la red la capacidad de aprender formas curvas complejas (no lineales).")
        with col_cnn2:
            st.markdown("**Reducción Espacial (MaxPool2D):**")
            st.markdown("Se utiliza una ventana móvil de `2x2`. De esos 4 píxeles, la red conserva únicamente el que tiene el valor más alto. Esto reduce el tamaño de la imagen a la mitad (128 ➜ 64 ➜ 32), reteniendo el rasgo más brillante e importante y ahorrando tiempo de cómputo.")

    # DESPLEGABLE 5: TUNING Y CLASIFICACIÓN
    with st.expander(" 5. Sintonización de Hiperparámetros y Clasificación Final"):
        st.markdown("### El Aporte del Estudio: Hyperparameter Tuning")
        st.markdown("El éxito del artículo base radica en que no se conformaron con la primera configuración de la red. Probaron sistemáticamente múltiples combinaciones para encontrar el modelo perfecto:")
        st.markdown("""
        1. **Optimizadores evaluados:** Adam, RMSprop, y SGD (Stochastic Gradient Descent).
        2. **Tasas de Dropout (Abandono):** 0.2 (20%) y 0.5 (50%). El dropout apaga neuronas al azar para obligar a la red a no depender de una sola característica visual.
        3. **Neuronas en la Capa Densa:** 512 vs 1024 neuronas.
        """)
        st.success(" **Conclusión Científica:** El **Modelo 3** logró el rendimiento máximo con una **precisión del 96.08%**. La configuración ganadora fue el optimizador **RMSprop** con un **Dropout de 0.2** y una Capa Densa de **512 neuronas**.")

        st.markdown("---")
        st.markdown("### Predicción Matemática Final")
        st.markdown("Tras extraer las características, el tensor se aplana (`Flatten`) en un vector unidimensional que pasa por capas densas (`nn.Linear`). La última capa tiene **4 neuronas** (una por cada tipo de diagnóstico).")

        st.markdown("**1. Función Softmax:** Convierte los valores numéricos brutos (*logits*) en una distribución de probabilidades que suma 1 (o 100%).")
        st.latex(r"P(y_i) = \frac{e^{z_i}}{\sum_{j=1}^{4} e^{z_j}}")

        st.markdown("**2. Función de Pérdida (Cross-Entropy Loss):** Mide qué tan equivocada estuvo la red comparando su predicción con el diagnóstico real del médico. El optimizador RMSprop utiliza esta ecuación para retropropagar el error (*Backpropagation*) y corregir los pesos de la red.")
        st.latex(r"\mathcal{L} = - \sum_{c=1}^{4} y_{o,c} \log(p_{o,c})")

# ==========================================
# SECCIÓN 3: TUTOR VIRTUAL
# ==========================================
elif menu == " Tutor Virtual":
    st.title(" Tutor Médico")
    for msg in st.session_state.chat_history:
        with st.chat_message(msg["role"]): st.markdown(msg["content"])
    if prompt := st.chat_input("Escribe tu duda..."):
        st.session_state.chat_history.append({"role": "user", "content": prompt})
        with st.chat_message("user"): st.markdown(prompt)
        with st.chat_message("assistant"):
            try:
                respuesta = modelo_llm.generate_content("Eres un profesor experto. Responde a: " + prompt)
                st.markdown(respuesta.text)
                st.session_state.chat_history.append({"role": "assistant", "content": respuesta.text})
            except Exception as e:
                st.error(f"Error de API: {str(e)}")

# ==========================================
# SECCIÓN 4: ZONA DE ESTUDIO
# ==========================================
elif menu == " Zona de Estudio":
    st.title(" Centro de Evaluación Gamificado")
    st.markdown("Personaliza tu sesión de estudio. Elige entre repasar conceptos rápidos, estudiar paso a paso con retroalimentación, o simular tu examen de grado.")

    tab_tarjetas, tab_guiado, tab_test = st.tabs([" Flashcards", " Estudio Guiado (Paso a Paso)", " Examen Paramétrico"])

    # ------------------------------------------
    # PESTAÑA 1: FLASHCARDS
    # ------------------------------------------
    with tab_tarjetas:
        st.subheader("Flashcards Interactivas de Repaso")
        flashcards = [
            {"pregunta": "¿Qué es el 'Overfitting' o Sobreajuste?", "respuesta": "Ocurre cuando el modelo memoriza los datos exactos de entrenamiento, volviéndose incapaz de generalizar frente a imágenes nuevas."},
            {"pregunta": "¿Para qué sirve el Aumento de Datos (Data Augmentation)?", "respuesta": "Para incrementar el dataset artificialmente mediante rotaciones y deformaciones, evitando el sobreajuste."},
            {"pregunta": "¿Qué labor cumple la función de activación ReLU?", "respuesta": "Introduce no-linealidad a la red matemática y apaga los valores de gradiente negativos (los convierte en ceros)."},
            {"pregunta": "¿Qué es un Meningioma?", "respuesta": "Es un tumor cerebral de crecimiento lento que se forma en las meninges (membranas protectoras del cerebro y médula)."}
        ]

        tarjeta_actual = flashcards[st.session_state.flashcard_index]
        texto_tarjeta = tarjeta_actual['respuesta'] if st.session_state.flashcard_flipped else tarjeta_actual['pregunta']

        html_tarjeta = f"<div style='background-color: #1E1E1E; padding: 40px; border-radius: 15px; text-align: center; border: 2px solid #4CAF50; min-height: 180px; display: flex; align-items: center; justify-content: center;'><h3 style='color: white; margin:0;'>{texto_tarjeta}</h3></div><br>"
        st.markdown(html_tarjeta, unsafe_allow_html=True)

        col_btn1, col_btn2 = st.columns(2)
        with col_btn1:
            if st.button("🔄 Voltear Tarjeta", use_container_width=True):
                st.session_state.flashcard_flipped = not st.session_state.flashcard_flipped
                st.rerun()
        with col_btn2:
            if st.button("⏭️ Siguiente Pregunta", use_container_width=True):
                st.session_state.flashcard_flipped = False
                st.session_state.flashcard_index = (st.session_state.flashcard_index + 1) % len(flashcards)
                st.rerun()

    # BANCO DE PREGUNTAS
    banco_preguntas = {
        "Fácil": [
            {"q": "¿Qué significa MRI en medicina?", "opciones": ["Magnetic Resonance Imaging", "Medical Resource Interface", "Multiple Ray Inspection"], "ans": "Magnetic Resonance Imaging", "exp": "MRI significa Imagen por Resonancia Magnética, una técnica no invasiva que usa campos magnéticos."},
            {"q": "¿Cuántas clases de salida tiene nuestra Red Neuronal?", "opciones": ["2", "4", "10"], "ans": "4", "exp": "Las 4 clases son: Glioma, Meningioma, Pituitario y Cerebro Sano."},
            {"q": "¿De qué tamaño ingresan las imágenes a la red después del preprocesamiento?", "opciones": ["128x128", "256x256", "512x512"], "ans": "128x128", "exp": "Se redimensionan a 128x128 para optimizar el consumo de memoria VRAM."},
            {"q": "¿Qué es un Meningioma?", "opciones": ["Tumor en huesos", "Tumor benigno en las membranas del cerebro", "Sangrado cerebral"], "ans": "Tumor benigno en las membranas del cerebro", "exp": "Crece en las meninges, las capas protectoras del cerebro."},
            {"q": "¿Para qué sirve el Data Augmentation?", "opciones": ["Comprimir el archivo", "Generar variantes de imágenes para evitar sobreajuste", "Colorear radiografías"], "ans": "Generar variantes de imágenes para evitar sobreajuste", "exp": "Aplica rotaciones y espejos para que la red no memorice posiciones."},
            {"q": "¿Qué significa CNN?", "opciones": ["Computer Neural Network", "Convolutional Neural Network", "Central Node Network"], "ans": "Convolutional Neural Network", "exp": "Red Neuronal Convolucional, ideal para procesar imágenes."},
            {"q": "¿Qué es un Glioma?", "opciones": ["Tumor en células gliales", "Tumor de piel", "Infección viral"], "ans": "Tumor en células gliales", "exp": "Ataca el cerebro y la médula, creciendo muy rápido."},
            {"q": "¿Qué es un Tensor en PyTorch?", "opciones": ["Una variable de texto", "Una matriz matemática multidimensional", "Un tipo de tumor"], "ans": "Una matriz matemática multidimensional", "exp": "Es la estructura de datos fundamental en PyTorch, similar a un array de NumPy."},
            {"q": "¿Qué glándula afecta el Tumor Pituitario?", "opciones": ["Tiroides", "Hipófisis (Pituitaria)", "Pineal"], "ans": "Hipófisis (Pituitaria)", "exp": "Afecta la hipófisis, descontrolando la producción hormonal."},
            {"q": "¿Qué plataforma se usó para obtener el Dataset del estudio?", "opciones": ["Kaggle", "GitHub", "StackOverflow"], "ans": "Kaggle", "exp": "El estudio descargó las 3264 imágenes de un repositorio médico en Kaggle."},
            {"q": "¿Cuántos canales de color tiene una imagen RGB?", "opciones": ["1", "3", "4"], "ans": "3", "exp": "Tiene 3 canales: Red (Rojo), Green (Verde) y Blue (Azul)."},
            {"q": "¿Qué es una Época (Epoch) en Machine Learning?", "opciones": ["Una pasada completa de todo el dataset por la red neuronal", "Un error del código", "El tiempo que tarda en cargar la imagen"], "ans": "Una pasada completa de todo el dataset por la red neuronal", "exp": "Una época termina cuando la red ha visto todas las imágenes de entrenamiento una vez."},
            {"q": "¿Para qué sirve la función de Pérdida (Loss)?", "opciones": ["Para borrar datos", "Para medir qué tan equivocada está la predicción de la IA", "Para acelerar la PC"], "ans": "Para medir qué tan equivocada está la predicción de la IA", "exp": "El objetivo del entrenamiento es minimizar este valor de pérdida."},
            {"q": "¿Qué hardware es ideal para entrenar CNNs?", "opciones": ["CPU", "GPU (Tarjeta Gráfica)", "Disco Duro HDD"], "ans": "GPU (Tarjeta Gráfica)", "exp": "Las GPUs tienen miles de núcleos ideales para las operaciones matriciales de las CNN."},
            {"q": "¿Qué porcentaje del dataset se suele usar para entrenamiento (Training)?", "opciones": ["10%", "50%", "80% o más"], "ans": "80% o más", "exp": "El artículo usa un 80% para entrenar, 10% para validar y 10% para testear."},
            {"q": "¿Qué significa Accuracy (Precisión)?", "opciones": ["El tamaño del modelo", "El porcentaje de predicciones correctas", "El tiempo de entrenamiento"], "ans": "El porcentaje de predicciones correctas", "exp": "Es la métrica principal. El estudio logró un 96% de Accuracy."},
            {"q": "¿Qué es PyTorch?", "opciones": ["Un editor de fotos", "Un framework de Deep Learning de código abierto", "Un lenguaje de programación"], "ans": "Un framework de Deep Learning de código abierto", "exp": "Desarrollado por Meta (Facebook), es el estándar en investigación de IA."},
            {"q": "¿Cómo se identifica un cerebro sano en la MRI?", "opciones": ["Por la ausencia de masas y simetría", "Por el color rojo brillante", "Por tener un cráneo grande"], "ans": "Por la ausencia de masas y simetría", "exp": "Los ventrículos son simétricos y no hay tejidos hiperintensos anormales."},
            {"q": "¿Por qué la IA médica es importante?", "opciones": ["Para reemplazar a los médicos", "Para reducir el error humano y la fatiga del radiólogo", "Para hacer los hospitales más caros"], "ans": "Para reducir el error humano y la fatiga del radiólogo", "exp": "La IA actúa como una 'segunda opinión' incansable y precisa."},
            {"q": "¿Qué es Deep Learning?", "opciones": ["Un sinónimo de base de datos", "Un subcampo de IA basado en redes neuronales profundas", "Un curso universitario"], "ans": "Un subcampo de IA basado en redes neuronales profundas", "exp": "Utiliza múltiples capas (profundidad) para extraer patrones complejos."}
        ],
        "Medio": [
            {"q": "¿Qué función de activación se usa en las capas ocultas para evitar valores negativos?", "opciones": ["Sigmoid", "ReLU", "Tangente Hiperbólica"], "ans": "ReLU", "exp": "ReLU (Rectified Linear Unit) convierte cualquier valor negativo en 0."},
            {"q": "¿Cuál es el objetivo de la capa MaxPooling2D?", "opciones": ["Añadir píxeles", "Reducir la dimensión conservando características importantes", "Calcular el error"], "ans": "Reducir la dimensión conservando características importantes", "exp": "Extrae el valor máximo de un cuadrante, reduciendo la imagen a la mitad."},
            {"q": "¿Qué optimizador se suele usar por excelencia en CNNs?", "opciones": ["Adam", "K-Means", "Random Forest"], "ans": "Adam", "exp": "Adam y RMSprop son los optimizadores de descenso de gradiente más eficaces."},
            {"q": "¿Qué porcentaje de Dropout se configuró en la red programada?", "opciones": ["10%", "30%", "90%"], "ans": "30%", "exp": "Se configuró `nn.Dropout(0.3)`, apagando el 30% de las neuronas."},
            {"q": "¿De cuántas imágenes consistía exactamente el dataset del estudio?", "opciones": ["1000", "3264", "5000"], "ans": "3264", "exp": "El estudio de Minarno usó 3264 imágenes divididas en 4 clases."},
            {"q": "¿Qué es el Overfitting?", "opciones": ["Cuando la red es muy rápida", "Cuando la red memoriza los datos y falla con imágenes nuevas", "Cuando el hardware se calienta"], "ans": "Cuando la red memoriza los datos y falla con imágenes nuevas", "exp": "Se evita usando Data Augmentation y Dropout."},
            {"q": "¿Qué hace `transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))`?", "opciones": ["Cambia el color a gris", "Convierte los píxeles al rango de -1 a 1", "Borra el fondo"], "ans": "Convierte los píxeles al rango de -1 a 1", "exp": "Aplica (X - 0.5) / 0.5 a cada canal RGB para centrar los datos matemáticamente."},
            {"q": "¿De qué tamaño fue el 'kernel_size' en las capas Conv2d de tu código?", "opciones": ["1", "3", "5"], "ans": "3", "exp": "Se usó `kernel_size=3`, que es un filtro matricial de 3x3 píxeles."},
            {"q": "¿Para qué sirve el parámetro 'padding=1' en la convolución?", "opciones": ["Para añadir un borde de ceros y no perder tamaño en los bordes de la imagen", "Para colorear de negro", "Para comprimir el archivo"], "ans": "Para añadir un borde de ceros y no perder tamaño en los bordes de la imagen", "exp": "Mantiene la dimensionalidad espacial después de aplicar el kernel de 3x3."},
            {"q": "¿Qué hace `transforms.RandomHorizontalFlip()`?", "opciones": ["Gira la imagen boca abajo", "Voltea la imagen horizontalmente como un espejo", "La recorta"], "ans": "Voltea la imagen horizontalmente como un espejo", "exp": "Es una técnica vital de Data Augmentation."},
            {"q": "¿Qué significa VRAM en el contexto de entrenamiento?", "opciones": ["Virtual Random Access Memory", "Video Random Access Memory (Memoria de GPU)", "Visual Reality"], "ans": "Video Random Access Memory (Memoria de GPU)", "exp": "Las imágenes médicas se redimensionan para no saturar la VRAM de la tarjeta gráfica."},
            {"q": "¿Cuál es la precisión máxima (Accuracy) lograda por el Modelo 3 en el paper?", "opciones": ["85.00%", "96.08%", "99.99%"], "ans": "96.08%", "exp": "Lograron 96.08% usando RMSprop y una capa densa de 512."},
            {"q": "¿Qué es el Learning Rate (Tasa de aprendizaje)?", "opciones": ["La velocidad a la que el optimizador actualiza los pesos de la red", "La velocidad del disco duro", "El tiempo que el humano tarda en aprender"], "ans": "La velocidad a la que el optimizador actualiza los pesos de la red", "exp": "Si es muy alto, la red no converge; si es muy bajo, tarda demasiado."},
            {"q": "¿Qué sucede en la Fase de Validación?", "opciones": ["Se entrena el modelo", "Se mide el rendimiento en datos no vistos para ajustar hiperparámetros", "Se guarda el archivo"], "ans": "Se mide el rendimiento en datos no vistos para ajustar hiperparámetros", "exp": "Sirve para saber si el modelo está sufriendo de Overfitting durante el proceso."},
            {"q": "¿Qué extrae la primera capa de convolución (Conv1)?", "opciones": ["Características simples como bordes y líneas", "El diagnóstico completo", "El nombre del paciente"], "ans": "Características simples como bordes y líneas", "exp": "Las capas tempranas ven bordes; las capas profundas ven texturas y formas de tumores."},
            {"q": "¿Por qué las imágenes médicas suelen ser en escala de grises pero se pasan a RGB?", "opciones": ["Para que se vean bonitas", "Porque modelos preentrenados y PyTorch esperan 3 canales", "Para imprimir a color"], "ans": "Porque modelos preentrenados y PyTorch esperan 3 canales", "exp": "Convertirlas a RGB (.convert('RGB')) asegura compatibilidad con los tensores (3, H, W)."},
            {"q": "¿Qué hiperparámetro de abandono usó el mejor modelo del paper?", "opciones": ["Dropout de 0.2", "Dropout de 0.5", "Dropout de 0.8"], "ans": "Dropout de 0.2", "exp": "El Modelo 3 ganador usó RMSprop, Dropout 0.2 y 512 neuronas densas."},
            {"q": "¿Qué es un 'Feature Map' (Mapa de Características)?", "opciones": ["Un mapa de Google", "La salida matricial después de aplicar una convolución", "Un gráfico de barras"], "ans": "La salida matricial después de aplicar una convolución", "exp": "Es la representación de las características que detectó el filtro en la imagen."},
            {"q": "¿Qué significa 'Hyperparameter Tuning'?", "opciones": ["Afina la música del sistema", "Prueba automáticamene múltiples configuraciones (optimizadores, neuronas) para hallar la mejor", "Borra parámetros inútiles"], "ans": "Prueba automáticamene múltiples configuraciones (optimizadores, neuronas) para hallar la mejor", "exp": "Es el núcleo del paper de Minarno: experimentar hasta lograr el 96%."},
            {"q": "¿Qué pasa si no usamos una función de activación no lineal como ReLU?", "opciones": ["El código da error", "La red neuronal actuaría como una simple regresión lineal, incapaz de resolver formas complejas", "Nada, es opcional"], "ans": "La red neuronal actuaría como una simple regresión lineal, incapaz de resolver formas complejas", "exp": "Las no linealidades permiten a la red 'doblar' el espacio matemático para separar clases."}
        ],
        "Difícil (Defensa de Grado)": [
            {"q": "¿Por qué el vector Flatten tiene un tamaño de 128 * 16 * 16?", "opciones": ["Porque hay 128 canales resultantes de imágenes de 16x16 tras 3 MaxPools", "Es un número aleatorio", "Porque la imagen era 16x16"], "ans": "Porque hay 128 canales resultantes de imágenes de 16x16 tras 3 MaxPools", "exp": "Inicia en 128x128. Tres capas MaxPool la reducen a la mitad cada una: 64, 32 y 16. La capa final Conv3 extrae 128 filtros."},
            {"q": "¿Qué fórmula matemática convierte los 'logits' en probabilidades que suman 1?", "opciones": ["Cross-Entropy", "Softmax", "MSE"], "ans": "Softmax", "exp": "Aplica una exponencial a los logits y los divide por la suma total, dando porcentajes precisos."},
            {"q": "¿Por qué se utiliza Cross-Entropy Loss en lugar de Mean Squared Error (MSE)?", "opciones": ["Es más rápida", "Es ideal para problemas probabilísticos de clasificación multiclase", "Penaliza pesos grandes"], "ans": "Es ideal para problemas probabilísticos de clasificación multiclase", "exp": "MSE es para regresión (números continuos), Cross-Entropy castiga severamente clasificaciones discretas erróneas."},
            {"q": "¿Qué comando es OBLIGATORIO antes de hacer inferencia (diagnóstico)?", "opciones": ["net.train()", "net.zero_grad()", "net.eval()"], "ans": "net.eval()", "exp": "Desactiva capas de regularización como Dropout. Durante el diagnóstico queremos usar el 100% de la red."},
            {"q": "¿Qué ocurre matemáticamente en la capa `nn.Linear(512, 4)`?", "opciones": ["Corta la imagen", "Multiplica una matriz de 512 variables por sus pesos para colapsarlas en 4 salidas", "Convierte a B/N"], "ans": "Multiplica una matriz de 512 variables por sus pesos para colapsarlas en 4 salidas", "exp": "Aplica la transformación lineal y = xA^T + b."},
            {"q": "¿Para qué sirve el contexto `with torch.no_grad():`?", "opciones": ["Acelera la descarga", "Desactiva el cálculo del gradiente, ahorrando memoria y CPU durante el diagnóstico", "Apaga la computadora"], "ans": "Desactiva el cálculo del gradiente, ahorrando memoria y CPU durante el diagnóstico", "exp": "Como no estamos entrenando (actualizando pesos), calcular gradientes es un desperdicio de recursos."},
            {"q": "¿Qué hace el comando `unsqueeze(0)` aplicado al tensor de la imagen?", "opciones": ["Le quita el color", "Añade una dimensión falsa de 'Batch' para que quede [1, 3, 128, 128]", "La comprime"], "ans": "Añade una dimensión falsa de 'Batch' para que quede [1, 3, 128, 128]", "exp": "Las CNN de PyTorch esperan un lote (Batch). Si pasas 1 imagen, debes simular que es un lote de tamaño 1."},
            {"q": "¿Qué es el algoritmo de Backpropagation (Retropropagación)?", "opciones": ["Un virus informático", "El método de cálculo para propagar el error hacia atrás y actualizar las derivadas parciales de los pesos", "Un sistema de respaldo"], "ans": "El método de cálculo para propagar el error hacia atrás y actualizar las derivadas parciales de los pesos", "exp": "Utiliza la regla de la cadena del cálculo diferencial para ajustar cada neurona."},
            {"q": "¿Por qué se aplicó `dim=1` en `F.softmax(outputs, dim=1)`?", "opciones": ["Porque es la dimensión que contiene las 4 clases de salida en el tensor de Batch", "Por estética", "Para sumar 1"], "ans": "Porque es la dimensión que contiene las 4 clases de salida en el tensor de Batch", "exp": "La dimensión 0 es el Batch. La dimensión 1 contiene los valores de las clases (logits)."},
            {"q": "¿Qué hace el optimizador RMSprop que lo hizo ganar en el artículo?", "opciones": ["Divide la imagen", "Adapta el Learning Rate dinámicamente dividiendo el gradiente por la raíz media cuadrada de gradientes pasados", "Es más lento"], "ans": "Adapta el Learning Rate dinámicamente dividiendo el gradiente por la raíz media cuadrada de gradientes pasados", "exp": "Ayuda a evitar oscilaciones violentas durante la optimización matemática."},
            {"q": "¿Qué significa el método `.item()` en PyTorch, como en `indice.item()`?", "opciones": ["Crea un ítem visual", "Extrae el valor numérico estándar de Python a partir de un Tensor de un solo elemento", "Borra el tensor"], "ans": "Extrae el valor numérico estándar de Python a partir de un Tensor de un solo elemento", "exp": "Es vital para poder imprimir el número en la pantalla o usarlo en diccionarios de Python."},
            {"q": "¿Qué son los 'Logits'?", "opciones": ["Un tipo de lógica", "Las salidas numéricas crudas (no normalizadas) de la última capa de la red antes del Softmax", "Un error de sistema"], "ans": "Las salidas numéricas crudas (no normalizadas) de la última capa de la red antes del Softmax", "exp": "Pueden ser números negativos o mayores a 1. El Softmax se encarga de arreglarlos."},
            {"q": "¿Qué hace el comando `modelo.load_state_dict()`?", "opciones": ["Descarga internet", "Inyecta los pesos y sesgos matemáticos preentrenados (.pth) dentro de la arquitectura vacía", "Muestra un diccionario"], "ans": "Inyecta los pesos y sesgos matemáticos preentrenados (.pth) dentro de la arquitectura vacía", "exp": "Es el equivalente a 'cargar el cerebro' del modelo desde el disco duro."},
            {"q": "¿Qué es el 'Stride' (Paso) en un MaxPooling2D(2,2)?", "opciones": ["El color del filtro", "La cantidad de píxeles que salta el filtro, por defecto es igual al tamaño del kernel (2)", "El ancho de la imagen"], "ans": "La cantidad de píxeles que salta el filtro, por defecto es igual al tamaño del kernel (2)", "exp": "Al saltar 2 píxeles, la imagen se reduce exactamente a la mitad sin solaparse."},
            {"q": "¿Cuál es el formato estándar de tensores de imagen en PyTorch?", "opciones": ["Alto, Ancho, Color", "Batch, Canales, Alto, Ancho (B, C, H, W)", "Color, Alto, Ancho"], "ans": "Batch, Canales, Alto, Ancho (B, C, H, W)", "exp": "PyTorch es 'Channel-First', a diferencia de TensorFlow que suele ser 'Channel-Last' (H, W, C)."},
            {"q": "¿Qué problema resuelve la Inicialización de Pesos (Weight Initialization)?", "opciones": ["El problema del desvanecimiento o explosión del gradiente", "El color de la interfaz", "El peso en MB del archivo"], "ans": "El problema del desvanecimiento o explosión del gradiente", "exp": "Si los pesos inician muy altos o bajos, la matemática de la red colapsa antes de poder aprender."},
            {"q": "¿Qué es Transfer Learning (Aprendizaje Transferido)?", "opciones": ["Transferir dinero", "Usar una red gigante preentrenada (como ResNet) y solo cambiar su última capa para tu proyecto", "Copiar en un examen"], "ans": "Usar una red gigante preentrenada (como ResNet) y solo cambiar su última capa para tu proyecto", "exp": "En tu proyecto no usaste Transfer Learning, sino que creaste una CNN a medida desde cero."},
            {"q": "¿Por qué es peligroso usar un Dropout muy alto, como 0.9?", "opciones": ["Apagará la computadora", "Apagar el 90% de las neuronas causa 'Underfitting', impidiendo que la red aprenda algo útil", "Hace que el modelo sea muy pesado"], "ans": "Apagar el 90% de las neuronas causa 'Underfitting', impidiendo que la red aprenda algo útil", "exp": "El flujo de información se interrumpe demasiado. Por eso el artículo halló que 0.2 era ideal."},
            {"q": "¿Qué indica el argumento `map_location=dispositivo` al cargar el modelo?", "opciones": ["Abre Google Maps", "Fuerza a los pesos guardados a cargarse en la RAM correcta (CPU o GPU) disponible en la web", "Busca el archivo en la nube"], "ans": "Fuerza a los pesos guardados a cargarse en la RAM correcta (CPU o GPU) disponible en la web", "exp": "Evita errores si el modelo se entrenó en GPU pero la web host se ejecuta en CPU."},
            {"q": "¿Cuál es la derivada de la función de pérdida usada para actualizar el optimizador?", "opciones": ["La integral de X", "El gradiente, calculado dinámicamente con `loss.backward()`", "Una constante de 0"], "ans": "El gradiente, calculado dinámicamente con `loss.backward()`", "exp": "Autograd de PyTorch computa las derivadas parciales automáticamente construyendo un grafo computacional."}
        ]
    }

    # ------------------------------------------
    # PESTAÑA 2: ESTUDIO GUIADO 
    # ------------------------------------------
    with tab_guiado:
        st.subheader("Entrenamiento Guiado")
        st.markdown("Responde una pregunta a la vez. El sistema evaluará tu respuesta y te brindará una **explicación instantánea** antes de continuar.")
        
        banco_total = banco_preguntas["Fácil"] + banco_preguntas["Medio"] + banco_preguntas["Difícil (Defensa de Grado)"]
        pregunta_actual = banco_total[st.session_state.thea_index]
        
        st.markdown(f"### Pregunta {st.session_state.thea_index + 1} de {len(banco_total)}")
        st.markdown(f"**{pregunta_actual['q']}**")
        
        if not st.session_state.thea_feedback:
            opcion = st.radio("Elige una opción:", pregunta_actual['opciones'], key="thea_radio", index=None)
            
            if st.button("Comprobar Respuesta", type="primary"):
                if opcion is None:
                    st.warning(" Selecciona una respuesta primero.")
                else:
                    st.session_state.thea_ans = opcion
                    st.session_state.thea_feedback = True
                    st.rerun()
        else:
            st.radio("Tu selección fue:", pregunta_actual['opciones'], key="thea_radio_disabled", index=pregunta_actual['opciones'].index(st.session_state.thea_ans), disabled=True)
            
            if st.session_state.thea_ans == pregunta_actual['ans']:
                st.success(" **¡Respuesta Correcta!**")
            else:
                st.error(f" **Respuesta Incorrecta.** La opción correcta era: **{pregunta_actual['ans']}**")
                
            st.info(f" **Retroalimentación:** {pregunta_actual['exp']}")
            
            if st.button("Continuar a la Siguiente Pregunta ➡️", type="primary"):
                st.session_state.thea_feedback = False
                st.session_state.thea_ans = None
                st.session_state.thea_index = (st.session_state.thea_index + 1) % len(banco_total)
                st.rerun()

    # ------------------------------------------
    # PESTAÑA 3: EXAMEN DINÁMICO MASIVO
    # ------------------------------------------
    with tab_test:
        st.subheader("Configuración del Examen de Simulación")
        
        col_ctrl1, col_ctrl2 = st.columns(2)
        with col_ctrl1:
            dif_seleccionada = st.selectbox("Selecciona la Dificultad:", ["Fácil", "Medio", "Difícil (Defensa de Grado)"])
        with col_ctrl2:
            
            num_preguntas = st.slider("Cantidad de preguntas a evaluar:", min_value=5, max_value=20, value=10)

        st.markdown("---")
        
        
        preguntas_activas = banco_preguntas[dif_seleccionada][:num_preguntas]
        valor_por_pregunta = 100.0 / num_preguntas

        with st.form("examen_dinamico"):
            respuestas_usuario = []
            
            for i, item in enumerate(preguntas_activas):
                st.markdown(f"**{i+1}. {item['q']}**")
                ans = st.radio("Opciones:", item['opciones'], key=f"q_{i}", index=None, label_visibility="collapsed")
                respuestas_usuario.append(ans)
                st.write("") 
                
            btn_calificar = st.form_submit_button("Entregar Examen y Calcular Nota", use_container_width=True)

        if btn_calificar:
            if None in respuestas_usuario:
                st.error(" Por favor, responde todas las preguntas antes de entregar el examen.")
            else:
                puntaje = 0
                for i, item in enumerate(preguntas_activas):
                    if respuestas_usuario[i] == item['ans']:
                        puntaje += valor_por_pregunta
                
                st.markdown("---")
                st.markdown(f"###  Tu Nota Final: {puntaje:.2f} / 100")
                st.progress(int(puntaje))
                
                if puntaje >= 90:
                    st.success(" ¡MAGNÍFICO! Tienes nivel de maestría en esta dificultad. ¡Prueba subiendo el nivel!")
                    st.balloons()
                elif puntaje >= 51:
                    st.warning(" ¡Aprobado! Pero aún hay margen de mejora. Usa la pestaña 'Estudio Guiado' para repasar.")
                else:
                    st.error(" Reprobado. El Tutor te recomienda volver a repasar los conceptos antes del siguiente intento.")
